hr/hr/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView

from poll.views import RegisterView, CreateUserProfile
from poll.view_poll import PollList

urlpatterns = [
    path('', PollList.as_view()),
    path('poll/', include('poll.urls', namespace='poll')),
    path('admin/', admin.site.urls, name='admin'),
    path('login/', LoginView.as_view(template_name='poll/login.html'), name='login'),  
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(  
        template_name='poll/register.html',  
		success_url=reverse_lazy('profile-create')  
    ), name='register'),
    path('profile-create/', CreateUserProfile.as_view(), name='profile-create'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hr/poll/urls.py
from django.urls import path, include

from .views import index
from .view_question import QuestionCreate, QuestionDetail, QuestionEdit, QuestionDelete, QuestionList
from .view_poll import PollList, PollCreate, PollEdit, PollDelete, PollDetail, PollSet
from .view_answer import AnswerDelete, AnswerEdit, AnswerList, AnswerCreate
from .view_kit import KitList, KitCreate, KitDelete, KitEdit
from .view_user import question_get_answer, check_poll, add_answers
from .view_checked_poll import UserCheckedPollList, AdminCheckedPollList
from .view_stat import get_stat
from .view_admin import UserList, QuestionUserList, QuestionPollList, PollUserList, PollQuestionList, UserPollList, UserQuestionList

app_name = 'poll'
urlpatterns = [
    path('', PollList.as_view(), name='index'), # Список опросов
    path("details/<int:pk>", PollDetail.as_view(), name="poll_details"), # Опрос подробно
    path('create/', PollCreate.as_view(), name='poll_create'), # Создать опрос
    path('edit/<int:pk>', PollEdit.as_view(), name='poll_edit'), # Редактировать опрос
    path('delete/<int:pk>', PollDelete.as_view(), name='poll_delete'), # Удалить опрос
    path('set/<int:pk>', PollSet.as_view(), name='poll_set'), # Присвоить опрос пользователю
    path("kit/list/<int:pk>", KitList.as_view(), name="kit_list"), # Список элементов связующей таблицы (балл вопроса в опросе)
    path('kit/create/<int:pk>', KitCreate.as_view(), name='kit_create'), # Создать элемент связующей таблицы (балл вопроса в опросе)
    path('kit/edit/<int:pk>', KitEdit.as_view(), name='kit_edit'), # Редактировать элемент связующей таблицы (балл вопроса в опросе)
    path('kit/delete/<int:pk>', KitDelete.as_view(), name='kit_delete'), # Удалить элемент связующей таблицы (балл вопроса в опросе)
    path('user/get_answer/<int:pk>', question_get_answer, name='question_get_answer'), # Список ответов в вопросе пользователя
    path("check/poll/<int:pk>", check_poll, name="check_poll"), # Список вопросов в опросе пользователя
    path('questions/', QuestionList.as_view(), name='question_list'), # Список вопросов
    path("questions/details/<int:pk>", QuestionDetail.as_view(), name="question_details"), # Вопрос подробно
    path('question/create/', QuestionCreate.as_view(), name='question_create'), # Создать вопрос
    path('question/edit/<int:pk>', QuestionEdit.as_view(), name='question_edit'), # Редактировать вопрос
    path('question/delete/<int:pk>', QuestionDelete.as_view(), name='question_delete'), # Удалить вопрос
    path("answer/list/<int:pk>", AnswerList.as_view(), name="answer_list"), # Список ответов
    path('answer/edit/<int:pk>', AnswerEdit.as_view(), name='answer_edit'), # Редактировать ответ
    path('answer/create/<int:pk>', AnswerCreate.as_view(), name='answer_create'), # Создать ответ
    path('answer/delete/<int:pk>', AnswerDelete.as_view(), name='answer_delete'), # Удалить ответ
    path('user/get_answer/add/', add_answers, name='add_answers'), # Сохранение ответов на вопрос пользователя в базе
    path('user_checked_poll/list', UserCheckedPollList.as_view(), name='user_checked_poll_list'), # Список пройденных опросов пользователя
    path('admin_checked_poll/list', AdminCheckedPollList.as_view(), name='admin_checked_poll_list'), # Список всех пройденных опросов
    path('stat/', get_stat, name='get_stat'), # Валидация опроса и сбор статистики
    path("user/list/", UserList.as_view(), name="user_list"), # Список пользователей
    path("question/user/list/<int:pk>", QuestionUserList.as_view(), name="question_user_list"), # Список пользователей вопроса
    path("question/poll/list/<int:pk>", QuestionPollList.as_view(), name="question_poll_list"), # Список опросов вопроса
    path("poll/user/list/<int:pk>", PollUserList.as_view(), name="poll_user_list"), # Список пользователей опроса
    path("poll/question/list/<int:pk>", PollQuestionList.as_view(), name="poll_question_list"), # Список вопросов опроса
    path("user/poll/list/<int:pk>", UserPollList.as_view(), name="user_poll_list"), # Список опросов пльзователя
    path("user/question/list/<int:pk>", UserQuestionList.as_view(), name="user_question_list"), # Список вопросов пользователя
]

hr/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
            <a class="navbar-brand" href="{% url 'poll:index' %}">HR ПОРТАЛ</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'poll:index' %}">Список опросов <span
                                class="sr-only">(current)</span></a>
                    </li>
                    
                    <li class="nav-item">
                        {% if user.userprofile.type_user == 2 %}
                        <a class="nav-link" href="{% url 'poll:user_checked_poll_list' %}">Завершенные опросы</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'poll:admin_checked_poll_list' %}">Завершенные опросы</a>
                        {% endif %}
                    </li>
                    
                    {% if user.userprofile.type_user == 1 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'poll:poll_create' %}">Создать опрос</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Вопросы
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'poll:question_list' %}">Список</a>
                            <a class="dropdown-item" href="{% url 'poll:question_create' %}">Создать</a>
                            
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'poll:user_list' %}">Список пользователей</a>
                    </li>
                    

                    
                    {% endif %}
                </ul>
                
                <p id="new_poll_pk" hidden="true">{{ new_poll_pk }}</p>
                <p id="ttl_poll" hidden="true">{{ ttl_poll }}</p>
                
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item active">
                        <p class="nav-link mb-0"><span id="timer_poll" class="badge badge-secondary mb-0"></span></p>
                    </li>
                    <li class="nav-item active">
                        <p class="nav-link mb-0"><span id="timer_question" class="badge badge-secondary mb-0"></span></p>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <p class="nav-link mb-0">Привет {{ user.username }}!</p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                    </li>
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin</a>
                    </li>
                    {% endif %}
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Зарегистрироваться</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    

    <div class="container mt-3 col-10">
        {% block content %}
        {% endblock %}
    </div>



    <script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


    <script>
        let timerPoll = document.querySelector('#timer_poll');
	    let timerQuestion = document.querySelector('#timer_question');
        let newPollPk = document.querySelector('#new_poll_pk').innerHTML;
        


        const updateTextPoll = () => { 
            timerPoll.innerHTML = 'Таймер опроса - ' + ('0' + String(countMinPoll)).slice(-2) + ':' + ('0' + String(countSecPoll)).slice(-2);
        }
        
        const updateTextQuestion = () => { 
            timerQuestion.innerHTML = 'Таймер вопроса - ' + ('0' + String(countMinQuestion)).slice(-2) + ':' + ('0' + String(countSecQuestion)).slice(-2);
        }
	
        const countDownPoll = () =>  { 
            let total = countSecPoll + countMinPoll * 60;
            timeInterval = setTimeout(countDownPoll, 1000);
            if (total <= 0) {
                clearTimeout(timeInterval)
                timerPoll.classList.remove("badge-secondary")
                timerPoll.classList.add("badge-danger")
                $.ajax({
                    url: 'http://127.0.0.1:8000/poll/stat/',
                    data: {newPollPk: newPollPk},
                    dataType: "html"
                });
            }
            if (countSecPoll > 0) {
                --countSecPoll;
            } else {
                if (countMinPoll != 0) {
                    countSecPoll = 59;
                    --countMinPoll;
                } else {
                    countSecPoll = 0;
                    countMinPoll = 0;
                }
            } 
            updateTextPoll()
        }
    

        const countDownQuestion = () =>  { 
            let total = countSecQuestion + countMinQuestion * 60;
            timeInterval = setTimeout(countDownQuestion, 1000);
            if (total <= 0) {
                clearTimeout(timeInterval)
                timerQuestion.classList.remove("badge-secondary")
                timerQuestion.classList.add("badge-danger")
            }
            if (countSecQuestion > 0) {
                --countSecQuestion;
            } else {
                if (countMinQuestion != 0) {
                    countSecQuestion = 59;
                    --countMinQuestion;
                } else {
                    countSecQuestion = 0;
                    countMinQuestion = 0;
                }
            } 
            updateTextQuestion()
        }

    
        if (document.querySelector('#ttl_poll')) {
            let ttlPoll = document.querySelector('#ttl_poll').innerHTML;
            if (ttlPoll > 0) {
                countSecPoll = ttlPoll % 60;
                countMinPoll = Math.floor(ttlPoll / 60);
                countDownPoll()
            }
        }
    
        if (document.querySelector('#ttl_question')) {
            let ttlQuestion = document.querySelector('#ttl_question').innerHTML;
            countSecQuestion = ttlQuestion % 60;
        	countMinQuestion = Math.floor(ttlQuestion / 60);
            countDownQuestion()
        }
    
    </script>

</body>

</html>