hr/hr/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView

from poll.views import RegisterView, CreateUserProfile
from poll.view_poll import PollList

urlpatterns = [
    path('', PollList.as_view()),
    path('poll/', include('poll.urls', namespace='poll')),
    path('admin/', admin.site.urls, name='admin'),
    path('login/', LoginView.as_view(template_name='poll/login.html'), name='login'),  
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(  
        template_name='poll/register.html',  
		success_url=reverse_lazy('profile-create')  
    ), name='register'),
    path('profile-create/', CreateUserProfile.as_view(), name='profile-create'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hr/poll/urls.py
from django.urls import path, include

from .views import index
from .view_question import QuestionCreate, QuestionDetail, QuestionEdit, QuestionDelete, QuestionList
from .view_poll import PollList, PollCreate, PollEdit, PollDelete, PollDetail, PollSet
from .view_answer import AnswerDelete, AnswerEdit, AnswerList, AnswerCreate
from .view_kit import KitList, KitCreate, KitDelete, KitEdit
from .view_user import question_get_answer, check_poll, add_answers
from .view_checked_poll import UserCheckedPollList, AdminCheckedPollList
from .view_stat import get_stat
from .view_admin import UserList, QuestionUserList, QuestionPollList, PollUserList, PollQuestionList, UserPollList, UserQuestionList

app_name = 'poll'
urlpatterns = [
    path('', PollList.as_view(), name='index'), # Список опросов
    path("details/<int:pk>", PollDetail.as_view(), name="poll_details"), # Опрос подробно
    path('create/', PollCreate.as_view(), name='poll_create'), # Создать опрос
    path('edit/<int:pk>', PollEdit.as_view(), name='poll_edit'), # Редактировать опрос
    path('delete/<int:pk>', PollDelete.as_view(), name='poll_delete'), # Удалить опрос
    path('set/<int:pk>', PollSet.as_view(), name='poll_set'), # Присвоить опрос пользователю
    path("kit/list/<int:pk>", KitList.as_view(), name="kit_list"), # Список элементов связующей таблицы (балл вопроса в опросе)
    path('kit/create/<int:pk>', KitCreate.as_view(), name='kit_create'), # Создать элемент связующей таблицы (балл вопроса в опросе)
    path('kit/edit/<int:pk>', KitEdit.as_view(), name='kit_edit'), # Редактировать элемент связующей таблицы (балл вопроса в опросе)
    path('kit/delete/<int:pk>', KitDelete.as_view(), name='kit_delete'), # Удалить элемент связующей таблицы (балл вопроса в опросе)
    path('user/get_answer/<int:pk>', question_get_answer, name='question_get_answer'), # Список ответов в вопросе пользователя
    path("check/poll/<int:pk>", check_poll, name="check_poll"), # Список вопросов в опросе пользователя
    path('questions/', QuestionList.as_view(), name='question_list'), # Список вопросов
    path("questions/details/<int:pk>", QuestionDetail.as_view(), name="question_details"), # Вопрос подробно
    path('question/create/', QuestionCreate.as_view(), name='question_create'), # Создать вопрос
    path('question/edit/<int:pk>', QuestionEdit.as_view(), name='question_edit'), # Редактировать вопрос
    path('question/delete/<int:pk>', QuestionDelete.as_view(), name='question_delete'), # Удалить вопрос
    path("answer/list/<int:pk>", AnswerList.as_view(), name="answer_list"), # Список ответов
    path('answer/edit/<int:pk>', AnswerEdit.as_view(), name='answer_edit'), # Редактировать ответ
    path('answer/create/<int:pk>', AnswerCreate.as_view(), name='answer_create'), # Создать ответ
    path('answer/delete/<int:pk>', AnswerDelete.as_view(), name='answer_delete'), # Удалить ответ
    path('user/get_answer/add/', add_answers, name='add_answers'), # Сохранение ответов на вопрос пользователя в базе
    path('user_checked_poll/list', UserCheckedPollList.as_view(), name='user_checked_poll_list'), # Список пройденных опросов пользователя
    path('admin_checked_poll/list', AdminCheckedPollList.as_view(), name='admin_checked_poll_list'), # Список всех пройденных опросов
    path('stat/', get_stat, name='get_stat'), # Валидация опроса и сбор статистики
    path("user/list/", UserList.as_view(), name="user_list"), # Список пользователей
    path("question/user/list/<int:pk>", QuestionUserList.as_view(), name="question_user_list"), # Список пользователей вопроса
    path("question/poll/list/<int:pk>", QuestionPollList.as_view(), name="question_poll_list"), # Список опросов вопроса
    path("poll/user/list/<int:pk>", PollUserList.as_view(), name="poll_user_list"), # Список пользователей опроса
    path("poll/question/list/<int:pk>", PollQuestionList.as_view(), name="poll_question_list"), # Список вопросов опроса
    path("user/poll/list/<int:pk>", UserPollList.as_view(), name="user_poll_list"), # Список опросов пльзователя
    path("user/question/list/<int:pk>", UserQuestionList.as_view(), name="user_question_list"), # Список вопросов пользователя
]

hr/poll/models/answer.py
from django.db import models

class Answer(models.Model):
    """
    Ответ на вопрос
    """
    text = models.CharField(max_length=150, verbose_name='текст ответа') # Текст ответа
    valid = models.BooleanField(verbose_name='валидность ответа') # Валидность ответа
    question = models.ForeignKey('Question', on_delete=models.CASCADE, related_name='answers', verbose_name='Вопрос') # Ссылка еа вопрос
    checked_count = models.IntegerField(null=True, blank=True, verbose_name='Количество отмеченных') # Количество отмеченных ответов
    valid_count = models.IntegerField(null=True, blank=True, verbose_name='Количество отмеченных верно') # Количество верно отмеченных ответов

    def __str__(self):
        return self.text

hr/poll/models/checked_answer.py
from django.db import models

class CheckedAnswer(models.Model):
    """
    Ответ на вопрос, на который получен ответ
    """
    answer = models.ForeignKey('Answer', on_delete=models.CASCADE, related_name='checked_answers', null=True, blank=True) # Ссылка на родительский ответ
    checked = models.BooleanField(null=True, blank=True) # Отмеченный ответ
    valid = models.BooleanField(null=True, blank=True) # Правильно отмеченный ответ
    question = models.ForeignKey('CheckedQuestion', on_delete=models.CASCADE, related_name='answers', null=True, blank=True) # Ссылка на вопрос, на который получен ответ
    
    def __str__(self):
        return self.answer.text

    

hr/poll/models/checked_poll.py
from django.db import models

class CheckedPoll(models.Model):
    """
    Пройденный опрос
    """
    poll = models.ForeignKey('Poll', on_delete=models.SET_NULL, null=True, verbose_name='опрос', related_name='checked_poll') # Ссылка на родительский опрос
    user = models.ForeignKey('UserProfile', on_delete=models.CASCADE, related_name='user_checked_polls', verbose_name='пользователь', null=True) # Ссылка на привязанного пользователя
    checked = models.BooleanField(null=True, blank=True) # Пройденный опрос
    valid = models.BooleanField(null=True, blank=True) # Правильно пройденный опрос
    rank = models.IntegerField(null=True, blank=True) # Полученный балл за опрос
    validated = models.BooleanField(null=True, blank=True, default=False) # Опрос, прошедший проверку на программные ошибки

    def __str__(self):
        return self.poll.name

hr/poll/models/checked_question.py
from django.db import models

class CheckedQuestion(models.Model):
    """
    Вопрос, на который получен ответ
    """
    question = models.ForeignKey('Question', on_delete=models.SET_NULL, verbose_name='вопрос', null=True, related_name='checked_questions') # Ссылка на родительский вопрос
    poll = models.ForeignKey('CheckedPoll', on_delete=models.CASCADE, related_name='questions') # Ссылка на пройденный опрос
    valid = models.BooleanField(null=True, blank=True) # Валидность ответа
    rank = models.IntegerField(null=True, blank=True) # Полученный балл

    def __str__(self):
        return self.question.text

hr/poll/models/kit.py
from django.db import models

class Kit(models.Model):
    """
    Таблица, связывающая опрос и вопрос с добавлением дополнительных полей
    """
    poll = models.ForeignKey('Poll', on_delete=models.CASCADE, related_name='kitpoll') # Ссылка на опрос
    question = models.ForeignKey('Question', on_delete=models.CASCADE, related_name='kitquestion') # Ссылка на вопрос
    rank = models.IntegerField() # Балл, получаемый за правильный ответ на вопрос в конкретном опросе

    def __str__(self):
        return self.poll.name

hr/poll/models/poll.py
from django.db import models

class Poll(models.Model):
    """
    Опрос
    """
    name = models.CharField(max_length=50, verbose_name='наименование опроса') # Наименоваие опроса
    time_limit = models.IntegerField(null=True, blank=True, verbose_name='предельное время (сек)') # Лимит времени на весь опрос
    date_pub = models.DateField(verbose_name='дата публикации') # Дата публикации опроса
    questions = models.ManyToManyField('Question', through='Kit', through_fields=('poll', 'question'), related_name='polls', verbose_name='Список вопросов', blank=True) # Список вопросов в опросе
    admin = models.ForeignKey('UserProfile', on_delete=models.PROTECT, related_name='admin_polls', verbose_name='администратор', null=True) # Администратор опроса
    user = models.ManyToManyField('UserProfile', related_name='user_polls', verbose_name='пользователь', blank=True) # Список назначенных пользователей
    test = models.BooleanField(null=True, blank=True) # Опрос или тест
    checked_count = models.IntegerField(null=True, blank=True) # Количество пройденных опросов
    valid_count = models.IntegerField(null=True, blank=True) # Колчество правильно пройденных опросов
    rank = models.IntegerField(null=True, blank=True) # Общий балл за опрос
    
    def __str__(self):
        return self.name

hr/poll/models/question.py
from django.db import models
from PIL import Image


class Question(models.Model):
    """
    Вопрос
    """
    class TypeOfQuestion(models.IntegerChoices):
        MONO = 1
        MULTI = 2

    text = models.CharField(max_length=150, verbose_name='текст вопроса') # Текст вопроса
    type = models.IntegerField('тип вопроса', choices=TypeOfQuestion.choices) # Тип вопроса по количеству ответов на вопрос
    image = models.ImageField(upload_to='images/%Y/%m/%d', null=True, blank=True, verbose_name='изображение') # Изображение к вопросу
    time_limit = models.IntegerField('предельное время (сек)', null=True, blank=True) # Лимит времени на вопрос
    checked_count = models.IntegerField(null=True, blank=True) # Количество вопросов, на которые получен ответ
    valid_count = models.IntegerField(null=True, blank=True) # Количество вопросов, на которые получен ответ правильно

    def __str__(self):
        return self.text

    # Изменяем размер изображения для сохранения
    def save(self):
        super().save()
        
        if self.image:
            img = Image.open(self.image.path)
            if img.height > 200 or img.width > 200:
                output_size = (200, 200)
                img.thumbnail(output_size)
                img.save(self.image.path)

hr/poll/models/user.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):  
    """
    Профиль пользователя
    """
    class TypeOfUser(models.IntegerChoices):
        MANAGER = 1
        USER = 2

    user = models.OneToOneField(User, on_delete=models.CASCADE) # Ссылка на класс User
    type_user = models.IntegerField('тип пользователя', choices=TypeOfUser.choices, null=True, blank=True) # Тип пользователя
    age = models.IntegerField('возраст') # Возраст

    def __str__(self):
        return self.user.username

hr/poll/forms.py
from datetime import date

from django import forms

from .models import UserProfile, Question, Poll, Answer, Kit, CheckedAnswer
  
  
class ProfileCreationForm(forms.ModelForm):  
    """
    Форма создания профиля пользователя
    """
    class Meta:  
        model = UserProfile  
        fields = ['age']


class QuestionForm(forms.ModelForm):
    """
    Форма создания и редактирования вопроса
    """
    class Meta:
        model = Question
        fields = ('text', 'type', 'image', 'time_limit')


class PollForm(forms.ModelForm):
    """
    Форма создания и редактирования опроса
    """
    date_pub = forms.DateField(label='Дата публикации', widget=forms.SelectDateWidget())
    admin = forms.ModelChoiceField(label='Администратор', queryset=UserProfile.objects.all(), widget=forms.widgets.Select(attrs={'size': 1}), disabled=True) # Изменяем размер виджет и ограничиваем доступ
    class Meta:
        model = Poll
        fields = ('name', 'date_pub', 'admin', 'time_limit', 'test')


class PollSetForm(forms.ModelForm):
    """
    Форма добавления к опросу пользователя
    """
    class Meta:
        model = Poll
        fields = ('user',)


class AnswerForm(forms.ModelForm):
    """
    Форма создания и редактирования ответа
    """
    question = forms.ModelChoiceField(label='Вопрос', queryset=Question.objects.all(), widget=forms.widgets.Select(attrs={'size': 1}), disabled=True) # Изменяем размер виджет и ограничиваем доступ
    class Meta:
        model = Answer
        fields = ('text', 'valid', 'question')


class KitForm(forms.ModelForm):
    """
    Форма добавления поля rank в связке опрос-вопрос
    """
    poll = forms.ModelChoiceField(label='Опрос', queryset=Poll.objects.all(), widget=forms.widgets.Select(attrs={'size': 1}), disabled=True) # Изменяем размер виджет и ограничиваем доступ
    class Meta:
        model = Kit
        fields = ('poll', 'question', 'rank')


class KitEditForm(forms.ModelForm):
    """
    Форма редактирования поля rank в связке опрос-вопрос
    """
    poll = forms.ModelChoiceField(label='Опрос', queryset=Poll.objects.all(), widget=forms.widgets.Select(attrs={'size': 1}), disabled=True) # Изменяем размер виджет и ограничиваем доступ
    question = forms.ModelChoiceField(label='Вопрос', queryset=Question.objects.all(), widget=forms.widgets.Select(attrs={'size': 1}), disabled=True) # Изменяем размер виджет и ограничиваем доступ
    class Meta:
        model = Kit
        fields = ('poll', 'question', 'rank')


# class UserQuestionForm(forms.Form):
#     """

#     """
#     poll = forms.ModelChoiceField(label='Опрос', queryset=Poll.objects.all(), widget=forms.widgets.Select(attrs={'size': 1}))
#     user = forms.ModelChoiceField(label='Пользователь', queryset=UserProfile.objects.all(), widget=forms.widgets.Select(attrs={'size': 1}))
#     question = forms.ModelChoiceField(label='Вопрос', queryset=Question.objects.all(), widget=forms.widgets.Select(attrs={'size': 1}))
#     admin = forms.ModelChoiceField(label='Администратор', queryset=UserProfile.objects.all(), widget=forms.widgets.Select(attrs={'size': 1}))


# class CheckedAnswerForm(forms.ModelForm):
#     """
    
#     """
#     answer = forms.ModelChoiceField(label='', queryset=CheckedAnswer.objects.all(), widget=forms.widgets.RadioSelect)
#     class Meta:
#         model = CheckedAnswer
#         fields = ('answer',)

hr/poll/views.py
from django.shortcuts import render
from django.views.generic import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse_lazy

from .forms import ProfileCreationForm

"""
"""

def index(request):  
    context = {}  
    return render(request, 'poll/index.html', context) 


class RegisterView(FormView):
    """
    Создание пользователя
    """
    form_class = UserCreationForm

    def form_valid(self, form):  
        form.save()  
        username = form.cleaned_data.get('username')  
        raw_password = form.cleaned_data.get('password1')  
        login(self.request, authenticate(username=username, password=raw_password))  
        return super(RegisterView, self).form_valid(form)  


class CreateUserProfile(FormView):  
    """
    Создание профиля пользователя
    """
    form_class = ProfileCreationForm
    template_name = 'poll/profile_create.html'
    success_url = reverse_lazy('poll:index')

    def dispatch(self, request, *args, **kwargs):  
        if self.request.user.is_anonymous:  
            return HttpResponseRedirect(reverse_lazy('poll:index'))  
        return super(CreateUserProfile, self).dispatch(request, *args, **kwargs)  
  
    def form_valid(self, form):  
        instance = form.save(commit=False)  
        instance.user = self.request.user  
        instance.save()  
        return super(CreateUserProfile, self).form_valid(form)

hr/poll/templates/poll/user/check_poll.html
{% extends 'base.html' %}

{% block title %}
Список вопросов
{% endblock %}

{% block content %}

<div class="container">
	{% if messages %}
		{% for message in messages %}
		<P {% if message.tags %} class="col-12 mt-5 alert {{ message.tags }}" {% endif %} role="alert">
			{{ message }}
		</p>
		{% endfor %}
	{% endif %}

	<div class="row">
		<div class="col-12 mt-5">
			<ul class="list-group">
				{% for question in questions %}
				<li class="list-group-item d-flex justify-content-between">
					{{ question.text }}
					<div>
						<a class="btn btn-secondary btn-sm"
							href="{% url 'poll:question_get_answer' pk=question.pk %}">Ответить на вопрос</a>
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>
<script>


</script>
{% endblock %}

hr/poll/templates/poll/user/question_get_answer.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        {% if messages %}
            {% for message in messages %}
            <P {% if message.tags %} class="col-12 mt-5 alert {{ message.tags }}" {% endif %} role="alert">
                {{ message }}
            </p>
            {% endfor %}
        {% endif %}

        <div class="col-12 mt-5">
            <p id="ttl_poll" hidden="true">{{ ttl_poll }}</p>
            <p id="ttl_question" hidden="true">{{ ttl_question }}</p>
            <p id="question_pk" hidden="true">{{ pk }}</p>
            <div class="card">
                {% if question.image %}
                <img src="{{ question.image.url }}" class="card-img-top" alt="..." style="max-width: 540px;">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ question.text }}</h5>
                    <ul class="list-group mt-3">
                        {% if not answers %}
                        {% for answer in question.answers.all %}
                        <li class="list-group-item">
                            {% if question.type == 2 %}
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="{{ forloop.counter0 }}">
                                <label class="form-check-label" for="{{ forloop.counter0 }}">
                                    {{ answer.text }}
                                </label>
                            </div>
                            {% endif %}
                            {% if question.type == 1 %}
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="exampleRadios"
                                    id="{{ forloop.counter0 }}" value="option{{ forloop.counter0 }}">
                                <label class="form-check-label" for="{{ forloop.counter0 }}">
                                    {{ answer.text }}
                                </label>
                            </div>
                            {% endif %}
                        </li>
                        {% endfor %}
                        {% endif %}

                        {% if answers %}
                        {% for answer in answers.all %}
                        <li class="list-group-item">

                            {% if question.type == 2 %}
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="{{ forloop.counter0 }}"
                                    {% if answer.checked %} checked {% endif %}>
                                <label class="form-check-label" for="{{ forloop.counter0 }}">
                                    {{ answer.answer.text }}
                                </label>
                            </div>
                            {% endif %}

                            {% if question.type == 1 %}
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="exampleRadios"
                                    id="{{ forloop.counter0 }}" value="option{{ forloop.counter0 }}"
                                    {% if answer.checked %} checked {% endif %}>
                                <label class="form-check-label" for="{{ forloop.counter0 }}">
                                    {{ answer.answer.text }}
                                </label>
                            </div>
                            {% endif %}

                        </li>
                        {% endfor %}
                        {% endif %}

                    </ul>
                    <div class="col-12 mt-3">
                        <a onclick="save_answer()" class="btn btn-outline-success btn-sm"
                            href="{{ return_path }}">Ответить</a>
                        <a class="btn btn-outline-secondary btn-sm" href="{{ return_path }}">Вернуться к списку
                            вопросов</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    // Запись ответов в базу
    function save_answer() {
        let l = document.querySelectorAll('.form-check-input').length;
        let pk = document.querySelector('#question_pk').innerHTML;
        let checked = '';
        for (let i = 0; i < l; i++) {
            if (document.getElementById(i).checked) {
                checked += '1';
            } else {
                checked += '0'
            }

        };

        $.ajax({
            url: 'add/',
            data: { checked: checked, pk: pk },
            dataType: "html"
        });
    }

</script>

{% endblock %}